[project]
name = "happyset"
version = '1.0.0'
authors = [  { name="Nao Yamanouchi" },]
description = "Frequently used processes are made into functions"
license = {text = "3-Clause BSD License"}
requires-python = ">=3.10.5"
